### ISSUE TITLE
Segmentation fault when a 

### ISSUE THREAD

**Issue by DemiMarie** [JeffBezanson/femtolisp#22]
The following expressions all cause a segmentation fault:
```scheme
((lambda ((a: (b 1))) #t))
((lambda ((a: b)) #t))
((lambda ((a (b 1))) a))
```
If `b` is bound to a variable (in the second case) or if is bound to a function that _does not throw an exception_ when applied to `1` (first and third cases), there is no segfault.  Nor is there a segfault if the exception is caught.

`gdb` reveals that, at least in the unbound variable case, the printer is called on an unbound variable.

**Comment by JeffBezanson** [comment]
Thank you, good catch! Fix coming.
