### ISSUE TITLE
Clarify location of implementation of map

### ISSUE THREAD

**Issue by qwitwa** [JeffBezanson/femtolisp#26]
The readme claims performance despite map not being a built-in, but a git-blame shows that map has been implemented by default as a built-in via the fl_map1 function since 2010, two years before the readme was written. Thus the readme is misleading.

**Comment by JeffBezanson** [comment]
Ah, you caught me :) I'll fix it.

`map` is a huge hot spot for the julia front end, so I had to move it to C to squeeze out every drop of performance.
