### ISSUE TITLE
can you give an example of how to call the pretty print procedure

### ISSUE THREAD

**Issue by hughbarney** [JeffBezanson/femtolisp#27]
Apolologies for this dumb question,

But I can also see that fl_print() looks like will do a pretty print on a bound symbol.

> (define (sq n) (* n n))
#fn("7000r1||T2;" [] sq)

> 
(pretty-print sq)
eval: variable pretty-print has no value
#0 (lambda)

;;; I can see that pretty-print is defined as write in aliases.scm

> 
(write sq)
#fn("7000r1||T2;" [] sq)#fn("7000r1||T2;" [] sq)

I would expect pretty-printing would output something like:

(define (sq n)
     (* n n))

;;If I do 
(write '(define (sq n) (* n n)) )

;; I get

(define (sq n)
  (* n n))(define (sq n)
  (* n n))

;; but I get it printed twice.

How do I pretty print a defined procedure ?

Thanks

**Comment by JeffBezanson** [comment]
I don't save the original symbolic expression used to define a procedure, so there's no way to get it from the function object.

At the prompt, the value appears to be printed twice because first it is printed by your call to `write`, then the returned value is printed by the REPL.

**Comment by hughbarney** [comment]
;;; the following works.  This is so I can mark a block in FemtoEmacs and get the code to be reformatted
;;  the block is cut and replaced with the output of the command below.

(define devnull (buffer))                                                                                                                            
                                                                                                                                                     
(with-output-to devnull (pretty-print '                                                                                                              
            (define (sq                                                                                                                              
    n)                                                                                                                                               
            (*                                                                                                                                       
     n  n                                                                                                                                            
  )                                                                                                                                                  
  )                                                                                                                                                  
                                                                                                                                                     
                                                                                                                                                     
  )                                                                                                                                                  
)                                                                                                                                                    
;;;;; here's the output
                                                                                                                                                     
(define (sq n)                                                                                                                                       
  (* n n))                                                                                                                                           
                                                                                                                                                     
Thanks
