### ISSUE TITLE
converting fl_lasterror to char *

### ISSUE THREAD

**Issue by hughbarney** [JeffBezanson/femtolisp#32]
Hi Jeff,

Whats the best way to convert fl_lasterror in C to a char \* such that I can return the string from a function.

Thanks
Hugh

**Comment by JeffBezanson** [comment]
You can call `fl_print` on an `ios_t` initialized with `ios_mem`, then call `ios_takebuf` to get the string. If you want the output the REPL would give, you need to call the lisp function `print-exception` inside `with-output-to-string` (this can be done by adding a new lisp function `print-exception-to-string`), then from C get the string pointer using `cvalue_data`.
