### ISSUE TITLE
Parsing Julia code

### ISSUE THREAD

**Issue by kskyten** [JeffBezanson/femtolisp#58]
I want to experiment with Julia and scheme interoperation. How do I parse Julia code with the included femtolisp repl?

**Comment by rgobbel** [comment]
In the src subdirectory of the Julia repository you'll find a few files with a .scm extension, including julia-parser.scm and julia-syntax.scm. Those are the actual lexical and parsing modules for the language.

**Comment by JeffBezanson** [comment]
Run `./julia --lisp` to get to its embedded femtolisp. The scheme function `julia-parse` parses julia code.

**Comment by kungfooman** [comment]
You need more hardcoded C functions to use `julia-parser.scm`, for example the implementation of `identifier-start-char?` which is in https://github.com/JuliaLang/julia/blob/master/src/flisp/julia_extensions.c
