### ISSUE TITLE
Question on C interoperability

### ISSUE THREAD

**Issue by thorstenhater** [JeffBezanson/femtolisp#61]
Hi,

I am looking for a small LISP-like language to embed into a C++ project and am interested
whether femtolisp fits the bill. My requirements specifically are these

- Define opaque objects
- Call C function on these objects

For objects, `void *` would be enough, but if I can make these proper citizens, it would 
be much appreciated.

Is there documentation/examples/advice on how to do this? I know of the use in Julia, but 
there no new datatypes are defined.

I also found the related `cvalue` interface, and can define some values with that, but how to
use `struct` (define struct, access members) and functions?

Cheers, 
Thorsten

**Comment by lassik** [comment]
Please take a look at [`define_opaque_type`](https://github.com/JeffBezanson/femtolisp/blob/0418c645cf31011412e2bfaaca497130b8d5a658/types.c#L70)  in `types.c`. For example, [the iostream type is defined using it](https://github.com/JeffBezanson/femtolisp/blob/0418c645cf31011412e2bfaaca497130b8d5a658/iostream.c#L443).

The representation of Scheme values is [laid out at the top of `flisp.h`](https://github.com/JeffBezanson/femtolisp/blob/0418c645cf31011412e2bfaaca497130b8d5a658/flisp.h#L7). Look at `value_t` and `TAG_*` and the rest.

**Comment by lassik** [comment]
Sorry, Lisp values :p Well, FemtoLisp almost passes for a Scheme implementation anyway.

**Comment by thorstenhater** [comment]
Thank you very much, that's what I needed.
